In [1]:
import torch
import numpy as np

In [8]:
n_past = 5

In [7]:
data = torch.arange(0,100,1).repeat(32).reshape(32, 100)
data

tensor([[ 0,  1,  2,  ..., 97, 98, 99],
        [ 0,  1,  2,  ..., 97, 98, 99],
        [ 0,  1,  2,  ..., 97, 98, 99],
        ...,
        [ 0,  1,  2,  ..., 97, 98, 99],
        [ 0,  1,  2,  ..., 97, 98, 99],
        [ 0,  1,  2,  ..., 97, 98, 99]])

In [10]:
mask = torch.ones(100, dtype=bool)

In [58]:
for i in range(1):
    past_index = i+2

    past_data = torch.roll(data, -past_index, 1)
    past_mask = torch.roll(mask, -past_index)

    past_mask[past_mask.shape[0]-i:] = False


In [59]:
print(past_data[0,:10])
print(data[0,:10])
print(past_mask[:10].int())

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)


In [35]:
print(past_data[0,90:])
print(data[0,90:])
print(past_mask[90:].int())

tensor([94, 95, 96, 97, 98, 99,  0,  1,  2,  3])
tensor([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=torch.int32)
